name: Second test
on:
    workflow_run:
    workflows: ["Flujo de trabajo 1"]
    types:
        - completed

jobs:
    build:
    runs-on: ubuntu-22.04
    steps:
        - name: test
        run: echo "Hola mundo"